const C=window.RECEPTION_CONFIG;const screens=[...document.querySelectorAll('.screen')];
document.documentElement.style.setProperty('--primary',C.theme.primary);document.documentElement.style.setProperty('--dark',C.theme.dark);document.documentElement.style.setProperty('--bg',C.theme.background);
const $=id=>document.getElementById(id);function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0)}
$('welcomeImage').src=C.welcomeImage;$('homeLogo').src=C.homeLogo||C.welcomeImage;$('businessName').textContent=C.businessName;$('bookingText').textContent=C.booking.phoneFirstText;$('bookingLink').href=C.booking.url;$('privacyNotice').textContent=C.safety.privateInfoMessage;
document.querySelectorAll('[data-screen]').forEach(el=>el.addEventListener('click',()=>show(el.dataset.screen)));document.querySelectorAll('.back').forEach(el=>el.addEventListener('click',()=>show('home')));$('welcome').addEventListener('click',()=>show('home'));$('welcome').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show('home')}});
C.services.forEach(([name,price,desc])=>{$('serviceList').insertAdjacentHTML('beforeend',`<div class="card"><div class="card-head"><span>${name}</span><strong>${price}</strong></div><p>${desc}</p></div>`)});C.hours.forEach(([day,time])=>$('hoursList').insertAdjacentHTML('beforeend',`<p><strong>${day}</strong><span>${time}</span></p>`));C.arrivalInfo.forEach(x=>$('arrivalList').insertAdjacentHTML('beforeend',`<div class="info-item">${x}</div>`));
$('phoneLink').href='tel:'+C.contact.phone.replace(/\s/g,'');$('phoneLink').textContent='Call '+C.contact.phone;$('emailLink').href='mailto:'+C.contact.email;$('emailLink').textContent='Email '+C.contact.email;
function addBubble(t,who='bot'){const d=document.createElement('div');d.className=`bubble ${who}`;d.textContent=t;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}function norm(t){return t.toLowerCase().replace(/[?!.,'’]/g,' ').replace(/\s+/g,' ').trim()}
function answer(q){const n=norm(q);if(/(chest pain|can't breathe|cannot breathe|unconscious|severe bleeding|medical emergency|ambulance)/.test(n))return C.safety.medicalMessage;if(/(diagnose|what is wrong with me|my injury|should i exercise|medical advice|pain in my|symptom)/.test(n))return C.safety.medicalMessage;if(/(password|card number|cvv|iban|medical record)/.test(n))return C.safety.privateInfoMessage;let best=null,bestScore=0;for(const item of C.qa){let score=item.keywords.filter(k=>n.includes(k)).length;if(score>bestScore){best=item;bestScore=score}}return best?best.answer:`I’m not certain about that, so I don’t want to give you the wrong information. Please choose Need Staff Help. This demo can be customised with the questions and approved answers for each business.`}
C.quickQuestions.forEach(q=>{const b=document.createElement('button');b.className='chip';b.textContent=q;b.onclick=()=>{addBubble(q,'user');setTimeout(()=>addBubble(answer(q)),120)};$('quickQuestions').appendChild(b)});$('askForm').addEventListener('submit',e=>{e.preventDefault();const q=$('askInput').value.trim();if(!q)return;addBubble(q,'user');$('askInput').value='';setTimeout(()=>addBubble(answer(q)),120)});$('askInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('askForm').requestSubmit()}});
let timer;function reset(){clearTimeout(timer);timer=setTimeout(()=>show('welcome'),C.idleSeconds*1000)}['touchstart','click','keydown'].forEach(evt=>document.addEventListener(evt,reset,{passive:true}));reset();
